name: lint_and_test
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - develop

env:
  DATABASE_URL: file:./db.sqlite
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: "test"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: lint
        run: pnpm lint
      - name: format
        run: pnpm format
      - name: test unit
        run: pnpm vitest run

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: build
        run: pnpm build

  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: build
        run: pnpm prisma validate

  validate-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
      - name: migrate
        run: pnpm prisma migrate reset --force
      - name: check migration
        run: pnpm prisma migrate diff --from-url file:./prisma/db.sqlite --to-schema-datamodel prisma/schema.prisma --exit-code
