name: lint_and_test
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./db.sqlite
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: lint
        run: pnpm lint
      - name: format
        run: pnpm format
      - name: test unit
        run: pnpm vitest run

  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./db.sqlite
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: "test"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: pnpm build

  validate-schema:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./db.sqlite
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: pnpm prisma validate

  validate-migration:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./db.sqlite
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: migrate
        run: pnpm prisma migrate reset --force
      - name: check migration
        run: pnpm prisma migrate diff --from-url file:./prisma/db.sqlite --to-schema-datamodel prisma/schema.prisma --exit-code
